development:
  adapter: postgresql
  database: booklist_development
  username: ono
  password: Astro
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: booklist_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: booklist_production
  pool: 5
  timeout: 5000